export const ActionTypes = {
  SET_EXERCISE: "SET_EXERCISE",
  ADD_EXERCISE: "ADD_EXERCISE",
  DELETE_EXERCISE: "DELETE_EXERCISE",
  SET_FOOD: "SET_FOOD",
  ADD_FOOD: "ADD_FOOD",
  DELETE_FOOD: "DELETE_FOOD",
  SET_GOAL: "SET_GOAL",
  ADD_GOAL: "ADD_GOAL",
  DELETE_GOAL: "DELETE_GOAL",
};
